#!/bin/sh

set -e

case "$1" in
    purge)
        rm -fr /var/log/zabbix-server
        rm -fr /var/run/zabbix
        rm -fr /etc/zabbix/alert.d
    ;;
esac

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/zabbix-server 1:2.2.7+dfsg-2~ -- "$@"
# End automatically added section
# Automatically added by dh_ucf
if [ "$1" = "purge" ]; then
	for ext in .ucf-new .ucf-old .ucf-dist ""; do
		rm -f "/etc/zabbix/zabbix_server.conf$ext"
	done
	
	if [ -x "`which ucf 2>/dev/null`" ]; then
		ucf --purge "/etc/zabbix/zabbix_server.conf"
	fi
	if [ -x "`which ucfr 2>/dev/null`" ]; then
		ucfr --purge zabbix-server-mysql "/etc/zabbix/zabbix_server.conf"
	fi
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d zabbix-server remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

