#!/bin/sh

set -e

# If /tmp/ZABBIX_PACKAGE_DEBUG file exists then enable debugging of this script.
#if [ -e /tmp/ZABBIX_PACKAGE_DEBUG ]; then
#    set -x
#fi

if [ "$1" = "configure" ]; then
    # Does the user 'zabbix' exist?
    if ! getent passwd zabbix > /dev/null 2>&1 ; then
        # Not yet. Create it.
        adduser --quiet --system --group --disabled-login --no-create-home --home /nonexistent zabbix
    fi

    chown zabbix:zabbix /var/log/zabbix-server -R
fi

# Automatically added by dh_installinit
# In case this system is running systemd, we need to ensure that all
# necessary tmpfiles (if any) are created before starting.
if [ -d /run/systemd/system ] ; then
	systemd-tmpfiles --create /usr/lib/tmpfiles.d/zabbix-server.conf >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/zabbix-server" ]; then
	update-rc.d zabbix-server defaults >/dev/null
fi
# End automatically added section
# Automatically added by dh_ucf
if [ "$1" = "configure" ]; then
	ucf "/usr/share/zabbix-server-mysql/zabbix_server.conf" "/etc/zabbix/zabbix_server.conf"
	ucfr zabbix-server-mysql "/etc/zabbix/zabbix_server.conf"
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/zabbix-server 1:2.2.7+dfsg-2~ -- "$@"
# End automatically added section

