#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/zabbix-server" ] || [ -e "/etc/init/zabbix-server.conf" ]; then
	invoke-rc.d zabbix-server stop || exit $?
fi
# End automatically added section
